Repository docksal/docksal, pull requests merged in 2018-12, with the labels that each got.

#866 Docker version updates
  .travis.yml
  bin/fin
  docs/content/core/volumes.md
  stacks/volumes-nfs.yml
Labels: 🏷enhancement

#832 Documents the core contribution boilerplate.
  docs/content/tools/drupal-contribution.md
Labels: 🏷documentation

#867 NFS and SMB mounts refactoring
  bin/fin
  docs/content/core/volumes.md
  stacks/volumes-nfs.yml
Labels: 🏷enhancement

#881 Documenting advanced use cases
  docs/content/service/cli/nodejs.md
  docs/content/troubleshooting/_index.md
  docs/content/troubleshooting/common-issues.md
  docs/content/troubleshooting/windows-smb.md
  docs/content/use-cases/_index.md
  docs/content/use-cases/auto-start-stop.md
  docs/content/use-cases/composer-command.md
  docs/content/use-cases/multiple-solr-cores.md
  docs/content/use-cases/multiple-web.md
  docs/content/use-cases/nodejs.md
  docs/content/use-cases/shared-cache-volumes.md
Labels: size/medium, 🏷documentation

#902 Only mount custom certificates folder to the proxy if it is mapped to Docker (fixes #850)
  bin/fin
Labels: 🏷bug

#918 changes default cli image to php 7.2
  docs/content/service/cli/settings.md
  docs/content/service/db/settings.md
  docs/content/service/web/settings.md
  docs/content/stack/checking-configuration.md
  docs/content/stack/extend-images.md
  docs/content/use-cases/docker-image.md
  stacks/services.yml
Labels: 🏷enhancement
