Repository docksal/docksal, pull requests merged in 2018-08, with the labels that each got.

#750 Fix help for project/global commands on Ubuntu 18.04.
  bin/fin
Labels: 🏷bug

#760 Fix path in cron docs
  docs/advanced/cron.md
Labels: 🏷documentation

#784 Handle Blackfire secrets as a special case. Closes #783
  bin/fin
  docs/tools/blackfire.md
  stacks/services.yml
Labels: 🏷bug, 🏷documentation, 🏷enhancement
