Repository docksal/docksal, pull requests merged in 2018-05, with the labels that each got.

#511 Allow dash and underscore in docker compose project name.
  bin/fin
Labels: enhancement

#533 Extending NGROK to use Variables
  bin/fin
  docs/tools/ngrok.md
Labels: enhancement

#542 Alpine Linux / PWD support
  bin/fin
Labels: enhancement, os/linux

#558 Updated options for projects.
  docs/getting-started/setup.md
Labels: documentation, enhancement

#555 Beautify and re-organize project wizard
  bin/fin
Labels: enhancement
