Repository docksal/docksal, pull requests merged in 2019-06, with the labels that each got.

#1078 Feature/new stacks
  docs/content/stack/zero-configuration.md
Labels: 🏷documentation

#1081 Allow disabling checking for updates
  bin/fin
  docs/content/stack/configuration-variables.md
Labels: 🏷enhancement

#1080 Adds SSH key forwarding support for cli
  bin/fin
  docs/content/stack/configuration-variables.md
  stacks/services.yml
Labels: 🏷enhancement

#1057 Export CLI user to a configurable variable
  bin/fin
  docs/content/stack/configuration-variables.md
Labels: discussion, 🏷enhancement
