Repository docksal/docksal, pull requests merged in 2019-12, with the labels that each got.

#1242 Revamp of Xdebug docs
  docs/content/tools/xdebug.md
  docs/static/images/xdebug-mapping-manual.png
  docs/static/images/xdebug-mapping.png
  docs/static/images/xdebug-phpstorm-automatic.png
  docs/static/images/xdebug-phpstorm-drush.png
  docs/static/images/xdebug-phpstorm-listener.png
  docs/static/images/xdebug-phpstorm-manual.png
  docs/static/images/xdebug-toggle-listener.png
  docs/static/images/xdebug-vscode.png
  docs/static/images/xdebug-vscode2.png
  stacks/services.yml
Labels: 🏷documentation

#1247 Improve performance and functionality of `fin bash`
  bin/fin
Labels: 🏷enhancement

#1248 Fix SSH_AUTH_SOCK being unset for custom commands
  bin/fin
Labels: 🏷bug

#1252 Add proxy variables to run cli
  bin/fin
Labels: 🏷enhancement
