Repository docksal/docksal, pull requests merged in 2019-10, with the labels that each got.

#1141 changes link of sample projects to the Docksal boilerplate list
  docs/content/troubleshooting/common-issues.md
Labels: 🏷documentation

#1138 Adds notice about spaces in project paths
  docs/content/getting-started/project-setup.md
Labels: 🏷documentation

#1115 Adds DRUSH_OPTIONS_URI to the cli service.
  stacks/services.yml
Labels: 🏷enhancement

#1154 Allow creating projects from a custom git repo
  bin/fin
Labels: 🏷enhancement

#1159 Fixed xdebug pages to use the correct files
  docs/content/tools/xdebug.md
Labels: 🏷documentation

#1155 Revised the Getting Started section of docs
  bin/fin
  docs/content/getting-started/project-setup.md
  docs/content/getting-started/setup.md
  docs/content/use-cases/docker-modes.md
  docs/content/use-cases/portable.md
  stacks/services.yml
Labels: 🏷documentation

#1175 adds Drupal 8 BLT version for project create option
  bin/fin
Labels: 🏷enhancement

#1189 adds message about RAM needed for composer projects
  docs/content/tools/composer.md
Labels: 🏷documentation

#1190 Adds Acquia BLT documentation
  docs/content/tools/acquia-blt.md
  docs/content/tools/composer.md
Labels: 🏷documentation

#1163 updates hugo config for docs site
  docs/config.toml
  docs/layouts/shortcodes/versions.html
Labels: 🏷documentation

#1178 Make health check timeout configurable
  bin/fin
  docs/content/stack/configuration-variables.md
Labels: 🏷enhancement

#1170 documentation for portainer
  docs/content/use-cases/portainer.md
  docs/static/images/portainer-container-console.png
  docs/static/images/portainer-container-logs.png
  docs/static/images/portainer-stack-details.png
  docs/static/images/portainer-stacks-list.png
Labels: 🏷documentation

#1192 fixes minor wording, punctuation issues
  docs/content/stack/configuration-labels.md
Labels: 🏷documentation

#1196 adds firewall information to troubleshooting docs
  docs/content/troubleshooting/common-issues.md
  docs/static/images/firewall.png
Labels: 🏷documentation

#1202 Make the is_tty function language independent
  bin/fin
Labels: 🏷enhancement

#1199 Refactor tests
  .travis.yml
  tests/cli-tools.bats
  tests/commands.bats
  tests/config.bats
  tests/general.bats
  tests/project.bats
  tests/scripts/acquia.sh
  tests/scripts/boilerplates.sh
  tests/scripts/commands.sh
  tests/scripts/config.sh
  tests/scripts/db.sh
  tests/scripts/drush.sh
  tests/scripts/pantheon.sh
  tests/scripts/platform.sh
  tests/scripts/project.sh
  tests/scripts/quicktest.sh
  tests/scripts/system.sh
  tests/scripts/wp.sh
  tests/system.bats
Labels: tests, 🏷enhancement

#1203 adds troubleshooting doc for greedy VPNs
  docs/content/troubleshooting/vpn.md
Labels: 🏷documentation

#1204 Remove Babun mentions
  bin/fin
  docs/content/fin/fin.md
  docs/content/troubleshooting/windows-smb.md
  docs/content/use-cases/docker-modes.md
  docs/content/use-cases/portable.md
Labels: 🏷documentation
