Repository docksal/docksal, pull requests merged in 2021-06, with the labels that each got.

#1504 updates list of addons
  docs/content/fin/addons.md
Labels: 🏷documentation

#1509 Replaced which with command in shell function wrappers
  bin/fin
Labels: 🏷enhancement

#1508 Issue 1507: Adding variable for 3.x wodby/xhprof.
  stacks/overrides-xhprof.yml
Labels: 🏷bug
