Repository docksal/docksal, pull requests merged in 2021-11, with the labels that each got.

#1591 Updating pantheon stack to use default MariaDB version.
  stacks/stack-pantheon.yml
Labels: 🏷enhancement

#1593 Disable project auto-start by default
  bin/fin
  docs/content/stack/configuration-variables.md
  docs/content/use-cases/project-auto-start-stop.md
Labels: 🏷enhancement, 🏷documentation

#1594 Add instructions for installing an addon globally
  docs/content/fin/addons.md
Labels: 🏷documentation
