Repository docksal/docksal, pull requests merged in 2022-02, with the labels that each got.

#1624 Fix stack-platformsh cli version.
  stacks/stack-platformsh.yml
Labels: 🏷bug

#1620 fin help updates
  bin/fin
  docs/content/fin/fin-help.md
  scripts/fin-help-generate.sh
Labels: 🏷documentation

#1625 Bump Docker versions
  bin/fin
  docs/content/getting-started/setup.md
Labels: 🏷enhancement, 🏷documentation

#1622 VirtualBox on macOS Monterey (12.x) support
  bin/fin
  docs/content/getting-started/setup.md
  docs/content/troubleshooting/common-issues.md
Labels: 🏷enhancement, 🏷documentation

#1552 Use Blackfire Agent v2
  stacks/services.yml
Labels: 🏷enhancement

#1632 Readme badges updates
  .github/workflows/default.yaml
  README.md
Labels: 🏷documentation

#1631 Image updates in stacks
  bin/fin
  docs/content/service/cli/settings.md
  docs/content/service/web/multiple-web.md
  docs/content/service/web/settings.md
  docs/content/stack/checking-configuration.md
  docs/content/stack/extend-images.md
  docs/content/stack/images-versions.md
  examples/.docksal/docksal.env
  stacks/services.yml
  stacks/stack-pantheon.yml
  stacks/stack-platformsh.yml
Labels: 🏷enhancement, 🏷documentation
